import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Header/Navbar";
import { getServerSession } from "next-auth";
import { authOptions } from "@/utils/authOptions";
import Footer from "@/components/Footer";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession(authOptions) as any;
  return (
    <html lang="en"  data-theme="light">
      <body className={raleway.className}>
      <div className="relative ">

      <div className='absolute left-0 top-0 w-full z-20'>
          <Navbar session={session}/>
          </div>

        <div>
        {children}
        </div>

        <div>
        <Footer/>
        </div>

      </div>
      </body>
    </html>
  );
}
